#
#  mcMMO configuration
#  Last updated on ${project.version}-b${BUILD_NUMBER}
#
#####

#
#  Settings for mcMMO in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    # Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    # Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: true
    # Allow mcMMO to check if a new version is available
    Update_Check: true
    Prefer_Beta: false
    # Allow mcMMO to inform other plugins of damage being dealt
    Event_Callback: true
    # Allow mcMMO to create zip backups for flatfile data on shutdown.
    Generate_Backups: true
    Power_Level_Cap: 0
    # Should mcMMO print out debug messages?
    Verbose_Logging: false
    # Should mcMMO over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true

Scoreboards:
    # Should mcMMO use scoreboards for /inspect?
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Inspect:
        Use: true
        Display_Time: 10
    # Should mcMMO use scoreboards for /mcrank?
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Mcrank:
        Use: true
        Display_Time: 10
    # Should mcMMO use scoreboards for /mcstats?
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Mcstats:
        Use: true
        Display_Time: 10
    # Should mcMMO use scoreboards for /mctop?
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Mctop:
        Use: true
        Display_Time: 10
    # Should mcMMO use scoreboards for /skillname (/mining, /fishing, etc.)?
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Skillname:
        Use: true
        Display_Time: 10
    # Should mcMMO display power levels on scoreboards? (below player name-tags)
    Power_Level:
        Use: false

Mob_Healthbar:
    # Default display for mob health bars - HEARTS, BAR, or DISABLED
    Display_Type: HEARTS
    # Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Time: 3

Database_Purging:
    # Amount of time (in hours) to wait between database purging
    # To only run at server start, set to 0
    # To never run, set to -1
    Purge_Interval: -1
    # Any user who hasn't connected in this many months will be purged from the database
    # To never purge old users, set to -1
    Old_User_Cutoff: 6

#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User_Name: UserName
        User_Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
    Server:
        Port: 3306
        Address: localhost

#
#  Settings for Hardcore mode
###
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 75.0
        Enabled:
            Acrobatics: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false
    Vampirism:
        Leech_Percentage: 5.0
        Enabled:
            Acrobatics: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false

#
#  Settings for SMP Mods
###
Mods:
    Tool_Mods_Enabled: false
    Armor_Mods_Enabled: false
    Block_Mods_Enabled: false
    Entity_Mods_Enabled: false

#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: true
        Cooldown: 240
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Prevent_Use_Underground: true
        Use_Cost: 1
        Recipe_Cost: 5
        Item_Name: FEATHER

#
#  Settings for Parties
###
Party:
    # Amount of time (in hours) to wait between automatically kicking old party members
    # To only run at server start, set to 0
    # To never kick old users, set to -1
    AutoKick_Interval: 12
    # Any user who hasn't connected in this many days will get kicked from their party
    Old_Party_Member_Cutoff: 7
    # Settings for party share modes
    Sharing:
        ExpShare_enabled: true
        ExpShare_bonus_base: 1.1
        ExpShare_bonus_increase: 1.05
        ExpShare_bonus_cap: 1.5
        ItemShare_enabled: true
        Range: 75.0

#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
    Cooldowns:
        Berserk: 240
        Blast_Mining: 60
        Giga_Drill_Breaker: 240
        Green_Terra: 240
        Serrated_Strikes: 240
        Skull_Splitter: 240
        Super_Breaker: 240
        Tree_Feller: 240
    Max_Seconds:
        Berserk: 0
        Blast_Mining: 0
        Giga_Drill_Breaker: 0
        Green_Terra: 0
        Serrated_Strikes: 0
        Skull_Splitter: 0
        Super_Breaker: 0
        Tree_Feller: 0
    Limits:
       Tree_Feller_Threshold: 500
    Tools:
        # Use more tool durability while using abilities. Set Durability_Loss to 0 to disable the extra durability damage.
        Durability_Loss: 1

#
#  Settings for Skills
#  Level cap of 0 for no limit
###
Skills:
    Acrobatics:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Prevent_AFK_Leveling: true
        Prevent_Dodge_Lightning: false
        Prevent_XP_After_Teleport: true
        Level_Cap: 0
    Archery:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Axes:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Excavation:
        Level_Cap: 0
    Fishing:
        Drops_Enabled: true
        Level_Cap: 0
    Herbalism:
        Level_Cap: 0
        Prevent_AFK_Leveling: true
    Mining:
        Level_Cap: 0
        Detonator_Name: FLINT_AND_STEEL
    Repair:
        Level_Cap: 0
        Anvil_Messages: true
        Anvil_Material: IRON_BLOCK
        Salvage_Anvil_Material: GOLD_BLOCK
        Salvage_tools: true
        Salvage_armor: true
        # Ask for a confirmation when a player tries to repair an enchanted item
        Confirm_Required: true
    Smelting:
        Level_Cap: 0
    Swords:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Taming:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
        Call_Of_The_Wild:
            Bones_Required: 10
            Fish_Required: 10
            Apples_Required: 10

            # Range to check for nearby pets when using Call Of The Wild, 0 will disable the check
            Range: 40.0
            # Amount of pets to summon when using Call Of The Wild
            Wolf_Amount: 1
            Ocelot_Amount: 1
            Horse_Amount: 1
    Unarmed:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
        Block_Cracker:
            SmoothBrick_To_CrackedBrick: true
    Woodcutting:
        Level_Cap: 0

#
#  Settings for Double Drops
###
Double_Drops:
    Herbalism:
        Brown_Mushroom: true
        Cactus: true
        Carrot: true
        Cocoa: true
        Crops: true
        Melon_Block: true
        Nether_Warts: true
        Potato: true
        Pumpkin: true
        Red_Mushroom: true
        Red_Rose: true
        Sugar_Cane_Block: true
        Vine: true
        Water_Lily: true
        Yellow_Flower: true
    Mining:
        Coal_Ore: true
        Diamond_Ore: true
        Emerald_Ore: true
        Ender_Stone: true
        Glowstone: true
        Gold_Ore: true
        Iron_Ore: true
        Lapis_Ore: true
        Mossy_Cobblestone: true
        Netherrack: true
        Obsidian: true
        Quartz_Ore: true
        Redstone_Ore: true
        Sandstone: true
        Stone: true
    Woodcutting:
        Oak: true
        Birch: true
        Spruce: true
        Jungle: true

#
#  Settings for commands
###
Commands:
    Generic:
        # If true, when using partial names in commands mcMMO will try to look for a match from
        # the offline players. Enabling this might slow the server down if there are a lot of offline players.
        Match_OfflinePlayers: false
    mcmmo:
        Donate_Message: true
    inspect:
        Max_Distance: 30.0
    ptp:
        Cooldown: 120
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Confirm_Required: true
        Request_Timeout: 300
        # If true, require players to have a mcmmo.commands.ptp.world.[WorldName] permission
        # to teleport to, from, or within any given world.
        World_Based_Permissions: false
    partychat:
        Chat_Prefix_Format: '[[GREEN]]([[WHITE]]{0}[[GREEN]])'

        # Allow mcMMO to use player display names in chat instead of their usernames
        Use_Display_Names: true
    adminchat:
        Chat_Prefix_Format: '[[AQUA]][[[WHITE]]{0}[[AQUA]]]'

        # Allow mcMMO to use player display names in chat instead of their usernames
        Use_Display_Names: true

#
#  Settings for particles
###
Particles:
    # These settings determine if fireworks should get launched when a player activates/deactivates an ability
    Ability_Activation: true
    Ability_Deactivation: true

    # Determines if the fireworks should be a large ball or a small one
    LargeFireworks: true

    # Use particle effect when these abilities trigger
    Dodge: true
    Bleed: true
    Greater_Impact: true

    # These settings determine if fireworks should get launched when a player levels-up,
    # this will happen by default for every 100 levels.
    LevelUp_Enabled: true
    LevelUp_Tier: 100
