#
#  mcMMO configuration
#  First generated on ${project.version}-b${BUILD_NUMBER}
#
#####

#
#  Settings for mcMMO in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    #Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    #Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: true
    #Allow mcMMO to inform other plugins of damage being dealt
    Event_Callback: true
    Power_Level_Cap: 0

#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User_Name: UserName
        User_Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
    Server:
        Port: 3306
        Address: localhost
#
#  Settings for Hardcore mode
###
Hardcore:
    Enabled: false
    Death_Stat_Loss_Penalty_Percentage: 75
    Vampirism: false
    Vampirism_Stat_Leech_Percentage: 5

#
#  Settings for SMP Mods
###
Mods:
    Tool_Mods_Enabled: false
    Armor_Mods_Enabled: false
    Block_Mods_Enabled: false

#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: true
        Feather_Cost: 10
        Item_ID: 288

#
#  Settings for Arcane Forging
###
Arcane_Forging:
    May_Lose_Enchants: true
    Rank_Levels:
        Rank_1: 100
        Rank_2: 250
        Rank_3: 500
        Rank_4: 750
    Keep_Enchants:
        Chance:
            Rank_4: 40
            Rank_3: 30
            Rank_2: 20
            Rank_1: 10
    Downgrades:
        Enabled: true
        Chance:
            Rank_4: 15
            Rank_3: 25
            Rank_2: 50
            Rank_1: 75

#
#  Settings for Fishing
###
Fishing:
  Drops_Enabled: true
  Tier_Levels:
    Tier1: 0
    Tier2: 200
    Tier3: 400
    Tier4: 600
    Tier5: 800

#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
    Cooldowns:
        Blast_Mining: 60
        Giga_Drill_Breaker: 240
        Berserk: 240
        Green_Terra: 240
        Skull_Splitter: 240
        Serrated_Strikes: 240
        Tree_Feller: 240
        Super_Breaker: 240
    Max_Seconds:
        Blast_Mining: 0
        Giga_Drill_Breaker: 0
        Berserk: 0
        Green_Terra: 0
        Skull_Splitter: 0
        Serrated_Strikes: 0
        Tree_Feller: 0
        Super_Breaker: 0
    Limits:
       Tree_Feller_Threshold: 500
    Tools:
        Durability_Loss_Enabled: true
        Durability_Loss: 2

#
#  Settings for Skills
#  Level cap of 0 for no limit
###
Skills:
    Acrobatics:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0 
    Archery:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Axes:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Excavation:
        Level_Cap: 0
        Requires_Shovel: true
    Fishing:
        Level_Cap: 0
    Herbalism:
        Level_Cap: 0
        Green_Thumb:
            Cobble_To_Mossy: true
            SmoothBrick_To_MossyBrick: true
            Dirt_To_Grass: true
    Mining:
        Level_Cap: 0
        Requires_Pickaxe: true
        Detonator_ID: 259
    Repair:
        Level_Cap: 0
        Anvil_Messages: true
        Anvil_ID: 42
    Swords:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Taming:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
        Call_Of_The_Wild:
            Bones_Required: 10
            Fish_Required: 10
    Unarmed:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Woodcutting:
        Level_Cap: 0
        Requires_Axe: true

#
#  Settings for Double Drops  
###
Double_Drops:
    Herbalism:
        Brown_Mushrooms: true
        Cacti: true
        Melons: true
        Nether_Warts: true
        Pumpkins: true
        Red_Mushrooms: true
        Red_Roses: true
        Sugar_Cane: true
        Vines: true
        Water_Lilies: true
        Wheat: true
        Yellow_Flowers: true
    Mining:
        Coal: true
        Diamond: true
        End_Stone: true
        Glowstone: true
        Gold: true
        Iron: true
        Lapis: true
        Moss_Stone: true
        Netherrack: true
        Obsidian: true
        Redstone: true
        Sandstone: true
        Stone: true
    Woodcutting:
        Oak: true
        Birch: true
        Spruce: true
        Jungle: true

#
#  Settings for XP distribution
###
Experience:
    Gains:
        Mobspawners:
            Enabled: false
        Multiplier:
            PVP: 1
            Global: 1.0
    PVP:
        Rewards: true
    Formula:
        Curve_Modifier: 20
        Multiplier:
            Swords: 1.0
            Taming: 1.0
            Acrobatics: 1.0
            Excavation: 1.0
            Herbalism: 1.0
            Unarmed: 1.0
            Woodcutting: 1.0
            Mining: 1.0
            Archery: 1.0
            Axes: 1.0
            Repair: 1.0
            Fishing: 1.0
    Fishing:
        Base: 800
    Excavation:
        Base: 40
    Woodcutting:
        Oak: 70
        Spruce: 80
        Birch: 90
        Jungle: 100
    Herbalism:
        Sugar_Cane: 30
        Cactus: 30
        Flowers: 100
        Pumpkin: 20
        Mushrooms: 150
        Wheat: 50
        Melon: 20
        Nether_Wart: 50
        Lily_Pads: 100
        Vines: 10
    Mining:
        Sandstone: 30
        Glowstone: 30
        Lapis: 400
        Obsidian: 150
        Stone: 30
        Netherrack: 30
        Gold: 350
        Redstone: 150
        Coal: 100
        Diamond: 750
        Iron: 250
        End_Stone: 150
        Moss_Stone: 30
    Taming:
        Animal_Taming:
            Wolf: 250
            Ocelot: 500
    Combat:
        Multiplier:
            Animals: 1.0
            Creeper: 4.0
            Skeleton: 3.0
            Spider: 2.0
            Zombie: 2.0
            Pig_Zombie: 3.0
            Enderman: 4.0
            Cave_Spider: 3.0
            Silverfish: 3.0
            Blaze: 3.0
            Magma_Cube: 2.0
            Ender_Dragon: 8.0
            Slime: 2.0
            Ghast: 3.0
            Iron_Golem: 2.0
#
#  Settings for commands
###
Commands:
    invite:
        Enabled: true
    mctop:
        Enabled: true
    xplock:
        Enabled: true
    inspect:
        Enabled: true
    mcc:
        Enabled: true
    mcremove:
        Enabled: true
    mmoedit:
        Enabled: true
    accept:
        Enabled: true
    mcstats:
        Enabled: true
    mcability:
        Enabled: true
    party:
        Enabled: true
    xprate:
        Enabled: true
    mcgod:
        Enabled: true
    mcmmo:
        Enabled: true
        Donate_Message: true
    mcrefresh:
        Enabled: true
    addxp:
        Enabled: true
    addlevels:
        Enabled: true
    ptp:
        Enabled: true
        Cooldown: 30
    p:
        Enabled: true
    a:
        Enabled: true