#
#  mcMMO configuration
#    First generated on ${project.version}-b${BUILD_NUMBER}
#
#####

#
#  Settings for mcMMO in general
###
General:
    Locale: en_us
    MOTD_Enabled: true
    #Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    #Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: true
    #Allow mcMMO to inform other plugins of damage being dealt
    Event_Callback: true
    Per_Level_Tools: false

#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User_Name: UserName
        User_Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
    Server:
        Port: 3306
        Address: localhost

#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: true
        Feather_Cost: 10
        Item_ID: 288
    Diamond:
        Axe: 750
        Hoe: 750
        Shovel: 750
        Sword: 750
        Pickaxe: 750
    Gold:
        Axe: 500
        Hoe: 500
        Shovel: 500
        Sword: 500
        Pickaxe: 500
    Iron:
        Axe: 250
        Hoe: 250
        Shovel: 250
        Sword: 250
        Pickaxe: 250
    Stone:
        Axe: 0
        Hoe: 0
        Shovel: 0
        Sword: 0
        Pickaxe: 0

#
#  Settings for Arcane Forging
###
Arcane_Forging:
    May_Lose_Enchants: true
    Rank_Levels:
        Rank_1: 100
        Rank_2: 250
        Rank_3: 500
        Rank_4: 750
    Keep_Enchants:
        Chance:
            Rank_4: 40
            Rank_3: 30
            Rank_2: 20
            Rank_1: 10
    Downgrades:
        Enabled: true
        Chance:
            Rank_4: 15
            Rank_3: 25
            Rank_2: 50
            Rank_1: 75

#
#  Settings for Fishing
###
Fishing:
  Drops_Enabled: true
  Tier_Levels:
    Tier1: 0
    Tier2: 200
    Tier3: 400
    Tier4: 600
    Tier5: 800

#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
    Cooldowns:
        Blast_Mining: 60
        Giga_Drill_Breaker: 240
        Berserk: 240
        Green_Terra: 240
        Skull_Splitter: 240
        Serrated_Strikes: 240
        Tree_Feller: 240
        Super_Breaker: 240
    Limits:
       Tree_Feller_Threshold: 500
    Tools:
        Durability_Loss_Enabled: true
        Durability_Loss: 2

#
#  Settings for Skills
#  Level cap of 0 for no limit
###
Skills:
    Acrobatics:
        Level_Cap: 0 
    Archery:
        Level_Cap: 0
    Axes:
        Level_Cap: 0
    Excavation:
        Level_Cap: 0
        Requires_Shovel: true
    Fishing:
        Level_Cap: 0
    Herbalism:
        Level_Cap: 0
        Green_Thumb:
            Cobble_To_Mossy: true
            SmoothBrick_To_MossyBrick: true
            Dirt_To_Grass: true
        Hunger_Bonus: true
        Instant_Wheat_Regrowth: true
    Mining:
        Level_Cap: 0
        Requires_Pickaxe: true
        Detonator_ID: 259
    Repair:
        Level_Cap: 0
        Anvil_Messages: true
        Anvil_ID: 42
        Can_Repair_Armor: true
        Can_Repair_Tools: true
        Leather:
            ID: 334
        String:
            ID: 287
        Stone:
            Level_Required: 0
            ID: 4
        Wood:
            ID: 5
        Gold:
            Level_Required: 0
            ID: 266
        Iron:
            Level_Required: 0
            ID: 265
        Diamond:
            Level_Required: 50
            ID: 264
    Swords:
        Level_Cap: 0
    Taming:
        Level_Cap: 0
        Call_Of_The_Wild:
            Bones_Required: 10
            Fish_Required: 10
    Unarmed:
        Level_Cap: 0
    Woodcutting:
        Level_Cap: 0
        Requires_Axe: true

#
#  Settings for XP distribution
###
Experience:
    Gains:
        Mobspawners:
            Enabled: false
        Multiplier:
            PVP: 1
            Global: 1.0
    PVP:
        Rewards: true
    Formula:
        Multiplier:
            Swords: 1.0
            Taming: 1.0
            Acrobatics: 1.0
            Excavation: 1.0
            Herbalism: 1.0
            Unarmed: 1.0
            Woodcutting: 1.0
            Mining: 1.0
            Archery: 1.0
            Axes: 1.0
            Repair: 1.0
            Fishing: 1.0
    Fishing:
        Base: 800
    Excavation:
        Base: 40
    Woodcutting:
        Oak: 70
        Spruce: 80
        Birch: 90
        Jungle: 100
    Herbalism:
        Sugar_Cane: 30
        Cactus: 30
        Flowers: 100
        Pumpkin: 20
        Mushrooms: 150
        Wheat: 50
        Melon: 20
        Nether_Wart: 50
        Lily_Pads: 100
        Vines: 10
    Mining:
        Sandstone: 30
        Glowstone: 30
        Lapis: 400
        Obsidian: 150
        Stone: 30
        Netherrack: 30
        Gold: 350
        Redstone: 150
        Coal: 100
        Diamond: 750
        Iron: 250
        End_Stone: 150
        Moss_Stone: 30
    Taming:
        Animal_Taming:
            Wolf: 250
            Ocelot: 500
    Combat:
        Multiplier:
            Animals: 1.0
            Creeper: 4.0
            Skeleton: 2.0
            Spider: 3.0
            Zombie: 2.0
            Pig_Zombie: 3.0
            Enderman: 2.0
            Cave_Spider: 3.0
            Silverfish: 3.0
            Blaze: 3.0
            Magma_Cube: 2.0
            Ender_Dragon: 8.0
            Slime: 2.0
            Ghast: 3.0
#
#  Settings for commands
###
Commands:
    invite:
        Enabled: true
    mctop:
        Enabled: true
    xplock:
        Enabled: true
    inspect:
        Enabled: true
    mcc:
        Enabled: true
    mcremove:
        Enabled: true
    mmoedit:
        Enabled: true
    accept:
        Enabled: true
    mcstats:
        Enabled: true
    mcability:
        Enabled: true
    party:
        Enabled: true
    xprate:
        Enabled: true
    mcgod:
        Enabled: true
    mcmmo:
        Enabled: true
        Donate_Message: true
    mcrefresh:
        Enabled: true
    addxp:
        Enabled: true
    addlevels:
        Enabled: true
    ptp:
        Enabled: true
        Cooldown: 30
    p:
        Enabled: true
        Display_Names: true
    a:
        Enabled: true
        Display_Names: true

#
#  Settings for Spout features
###
Spout:
    Menu:
        Key: KEY_M
    XP:
        Bar:
            Enabled: true
            X_POS: 95
            Y_POS: 6
        Icon:
            Enabled: true
            X_POS: 78
            Y_POS: 2
    Party:
        HUD:
            Show_Faces: true
            Enabled: true
            Show_Display_Name: false
    HUD:
        Default: STANDARD
        Retro:
            Colors:
                Swords:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Taming:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Acrobatics:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Border:
                    BLUE: 0.0
                    GREEN: 0.0
                    RED: 0.0
                Background:
                    BLUE: 0.75
                    GREEN: 0.75
                    RED: 0.75
                Woodcutting:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Archery:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Axes:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Repair:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Fishing:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Excavation:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Herbalism:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Unarmed:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3
                Mining:
                    BLUE: 0.75
                    GREEN: 0.3
                    RED: 0.3